name: flutter_awsome_video_grid_example
description: Example app demonstrating the flutter_awsome_video_grid package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Package dependency
  flutter_awsome_video_grid:
    path: ../

  # Required for package to work
  flutter_riverpod: ^2.6.1
  cached_network_image: ^3.4.1
  cached_video_player_plus: ^3.0.3
  visibility_detector: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
